### company 생성(실패 cors문제)
POST http://localhost:8080/company
Content-Type: application/json

{
  "name" : "구글",
  "email" : "google@gmail.com",
  "phone" : "1-010-1234-5678"
}

### 입사지원 하기
POST http://localhost:8080/appliedCompanies
Content-Type: application/json

{
  "applicantId": 1,
  "name" : "지원자명",
  "email" : "applicant@naver.com",
  "phoneNumber" : "010-1111-2222",  
  "companyId": 1
  }
}

### 입사지원 수정하기
PUT http://localhost:8080/appliedCompanies
Content-Type: application/json

{
  "applicantId": 1,
  "name" : "지원자명변경",
  "email" : "이메일 변경@naver.com",
  "phoneNumber" : "전번변경010-1111-2222",  
  "companyId": 1
  }
}

### 입사지원 전체 목록
GET http://localhost:8080/appliedCompanies
